<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/helpers.php';exigirAdmin();
$registros=db()->query("SELECT a.*,ua.nome ator_nome,ua.nome_usuario ator_login,ue.nome efetivo_nome,ue.nome_usuario efetivo_login,ut.nome alvo_nome,ut.nome_usuario alvo_login FROM auditoria a LEFT JOIN usuarios ua ON ua.id=a.usuario_id LEFT JOIN usuarios ue ON ue.id=a.usuario_efetivo_id LEFT JOIN usuarios ut ON a.entidade='usuario' AND CAST(a.entidade_id AS UNSIGNED)=ut.id ORDER BY a.id DESC LIMIT 500")->fetch_all(MYSQLI_ASSOC);
$acoes=['login_sucesso'=>'Login realizado com sucesso','login_falhou'=>'Senha incorreta','login_bloqueado'=>'Tentativa em usuário bloqueado','usuario_bloqueado_5_tentativas'=>'Usuário bloqueado após 5 tentativas','usuario_cadastrado'=>'Novo usuário cadastrado','email_confirmado'=>'E-mail do cadastro confirmado','codigo_recuperacao_enviado'=>'Código de recuperação enviado','senha_alterada'=>'Senha alterada pelo usuário','senha_redefinida'=>'Senha redefinida por código','admin_aprovar_usuario'=>'Usuário aprovado pelo administrador','admin_bloquear_usuario'=>'Usuário bloqueado pelo administrador','admin_desbloquear_usuario'=>'Usuário desbloqueado pelo administrador','admin_entrou_como_usuario'=>'Administrador entrou na conta do usuário','admin_saiu_da_conta_representada'=>'Administrador voltou à própria conta','processo_criado'=>'Processo cadastrado','processo_editado'=>'Processo editado','processo_salvo'=>'Processo atualizado','processo_concluido'=>'Processo concluído','status_processo_alterado'=>'Status do processo alterado','observacao_processo_alterada'=>'Observações do processo alteradas','comentario_processo_adicionado'=>'Comentário adicionado ao processo','anexo_processo_adicionado'=>'Anexo adicionado ao processo','processo_excluido'=>'Processo excluído','procurador_salvo'=>'Procurador cadastrado ou atualizado'];
function dataAuditoria(string $data):string{$d=new DateTime($data);return $d->format('d/m/Y H:i:s');}
function identidadeAuditoria(?string $nome,?string $login):string{return $nome?trim($nome).($login?' ('.$login.')':''):($login?'Usuário removido ('.$login.')':'-');}
function valorAuditoria($v):string{if(is_array($v))return implode(', ',array_map('strval',$v));if($v===null||$v==='')return 'não informado';return (string)$v;}
function detalhesAuditoria(array $r):array{$d=json_decode($r['detalhes']??'',true)?:[];$linhas=[];if(isset($d['tentativas_invalidas_zeradas']))$linhas[]=(int)$d['tentativas_invalidas_zeradas']===0?'Contador de tentativas permaneceu em zero.':'Login correto: '.(int)$d['tentativas_invalidas_zeradas'].' tentativa(s) inválida(s) foram zeradas.';if(isset($d['tentativa']))$linhas[]='Tentativa inválida número '.(int)$d['tentativa'].' de 5.';foreach($d['mudancas']??[] as $campo=>$m)$linhas[]=ucfirst(str_replace('_',' ',$campo)).': “'.valorAuditoria($m['antes']??null).'” → “'.valorAuditoria($m['depois']??null).'”.';if(isset($d['nome_usuario']))$linhas[]='Nome de usuário: '.$d['nome_usuario'].'.';if(isset($d['status'])&&!isset($d['mudancas']))$linhas[]='Novo status: '.$d['status'].'.';if(isset($d['comentario_id']))$linhas[]='Comentário registrado no histórico do processo.';if(isset($d['anexo_id']))$linhas[]='Arquivo anexado: '.($d['nome']??'nome não disponível').'.';return $linhas;}
$identidadesHistoricas=[];foreach($registros as $registro){if($registro['entidade']==='usuario'&&$registro['entidade_id']){$d=json_decode($registro['detalhes']??'',true)?:[];$chave=(string)$registro['entidade_id'];if(!isset($identidadesHistoricas[$chave]))$identidadesHistoricas[$chave]=['nome'=>null,'login'=>null];if(!empty($d['nome']))$identidadesHistoricas[$chave]['nome']=$d['nome'];if(!empty($d['nome_usuario']))$identidadesHistoricas[$chave]['login']=$d['nome_usuario'];}}
$titulo='Auditoria';require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div><h1>Auditoria</h1><p>Veja de forma clara quem realizou cada ação e qual conta foi utilizada.</p></div></section>
<section class="audit-help"><div><strong>Autor real</strong><span>Pessoa que iniciou a ação. Quando o ADMIN entra em outra conta, continua aparecendo como autor real.</span></div><div><strong>Conta utilizada</strong><span>Conta em que a ação aconteceu. Normalmente é igual ao autor; muda durante o acesso administrativo.</span></div><div><strong>Usuário relacionado</strong><span>Conta aprovada, bloqueada, recuperada ou envolvida na ação.</span></div></section>
<section class="panel audit-list"><div class="table-wrap"><table><thead><tr><th>Data e hora</th><th>Autor real</th><th>Conta utilizada</th><th>Ação realizada</th><th>Usuário/registro relacionado</th><th>Detalhes</th><th>IP</th></tr></thead><tbody>
<?php if(!$registros):?><tr><td colspan="7" class="empty">Nenhuma ação registrada.</td></tr><?php endif;?>
<?php foreach($registros as $r):
 $acao=$acoes[$r['acao']]??ucfirst(str_replace('_',' ',$r['acao']));
 $acaoDoProprioUsuario=in_array($r['acao'],['usuario_cadastrado','email_confirmado','codigo_recuperacao_enviado','login_sucesso','login_falhou','login_bloqueado','usuario_bloqueado_5_tentativas','senha_alterada','senha_redefinida'],true);
 $jsonDetalhes=json_decode($r['detalhes']??'',true)?:[];$snapshot=$jsonDetalhes['_identidades']??[];$historica=$identidadesHistoricas[(string)$r['entidade_id']]??['nome'=>null,'login'=>null];
 $autorNome=$r['ator_nome']?:($snapshot['autor']['nome']??($acaoDoProprioUsuario?($r['alvo_nome']?:$historica['nome']):null));$autorLogin=$r['ator_login']?:($snapshot['autor']['login']??($acaoDoProprioUsuario?($r['alvo_login']?:$historica['login']):null));
 $efetivoNome=$r['efetivo_nome']?:($snapshot['conta']['nome']??($acaoDoProprioUsuario?($r['alvo_nome']?:$historica['nome']):null));$efetivoLogin=$r['efetivo_login']?:($snapshot['conta']['login']??($acaoDoProprioUsuario?($r['alvo_login']?:$historica['login']):null));
 $autor=identidadeAuditoria($autorNome,$autorLogin);$conta=identidadeAuditoria($efetivoNome,$efetivoLogin);$detalhes=detalhesAuditoria($r);
 $relacionado=$r['alvo_nome']?identidadeAuditoria($r['alvo_nome'],$r['alvo_login']):(($r['entidade']?:'Registro').($r['entidade_id']?' #'.$r['entidade_id']:''));
?><tr><td class="cell-nowrap"><strong><?=e(dataAuditoria($r['criado_em']))?></strong></td><td><span class="audit-person"><?=e($autor==='-'?'Sistema automático':$autor)?></span></td><td><span class="audit-account"><?=e($conta)?></span><?php if($autor!=='-'&&$conta!=='-'&&$autor!==$conta):?><small class="admin-access-label">Acesso pelo ADMIN</small><?php endif;?></td><td><span class="audit-action"><?=e($acao)?></span></td><td><?=e($relacionado)?></td><td class="audit-details"><?php if($detalhes):?><ul><?php foreach($detalhes as $linha):?><li><?=e($linha)?></li><?php endforeach;?></ul><?php else:?><span class="muted-text">Sem informações adicionais</span><?php endif;?></td><td class="cell-nowrap"><?=e($r['ip']==='::1'?'localhost':($r['ip']?:'-'))?></td></tr><?php endforeach;?>
</tbody></table></div></section><?php require __DIR__.'/includes/footer.php';?>
