<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/helpers.php';exigirLogin();
$id=(int)($_GET['id']??0);if($id<=0){http_response_code(404);exit('Processo inválido.');}
$q=db()->prepare("SELECT p.*,u.nome criador_nome,proc.procuradores_nomes FROM prazos p LEFT JOIN usuarios u ON u.id=p.criado_por LEFT JOIN (SELECT pp.prazo_id,GROUP_CONCAT(pr.nome ORDER BY pr.nome SEPARATOR ', ') procuradores_nomes FROM prazo_procuradores pp JOIN procuradores pr ON pr.id=pp.procurador_id GROUP BY pp.prazo_id) proc ON proc.prazo_id=p.id WHERE p.id=?");$q->bind_param('i',$id);$q->execute();$processo=$q->get_result()->fetch_assoc();if(!$processo){http_response_code(404);exit('Processo não encontrado.');}
$q=db()->prepare("SELECT a.*,ua.nome ator,ue.nome efetivo FROM auditoria a LEFT JOIN usuarios ua ON ua.id=a.usuario_id LEFT JOIN usuarios ue ON ue.id=a.usuario_efetivo_id WHERE a.entidade='processo' AND a.entidade_id=? ORDER BY a.id ASC");$idTexto=(string)$id;$q->bind_param('s',$idTexto);$q->execute();$historico=$q->get_result()->fetch_all(MYSQLI_ASSOC);
$q=db()->prepare('SELECT c.*,u.nome autor FROM processo_comentarios c LEFT JOIN usuarios u ON u.id=c.usuario_id WHERE c.prazo_id=? ORDER BY c.id DESC');$q->bind_param('i',$id);$q->execute();$comentarios=$q->get_result()->fetch_all(MYSQLI_ASSOC);
$q=db()->prepare('SELECT a.*,u.nome autor FROM processo_anexos a LEFT JOIN usuarios u ON u.id=a.usuario_id WHERE a.prazo_id=? ORDER BY a.id DESC');$q->bind_param('i',$id);$q->execute();$anexos=$q->get_result()->fetch_all(MYSQLI_ASSOC);
$temCadastro=false;foreach($historico as $h)if($h['acao']==='processo_criado')$temCadastro=true;
$rotulos=['numero_processo'=>'Número do processo','assunto'=>'Assunto','data_entrada'=>'Data de entrada','data_vencimento'=>'Data de vencimento','status'=>'Status','observacoes'=>'Observações','procuradores'=>'Procuradores vinculados'];
$acoes=['processo_criado'=>'Processo cadastrado','processo_editado'=>'Processo editado','processo_salvo'=>'Processo atualizado','processo_concluido'=>'Processo concluído','status_processo_alterado'=>'Status alterado','observacao_processo_alterada'=>'Observações alteradas','comentario_processo_adicionado'=>'Comentário adicionado','anexo_processo_adicionado'=>'Anexo adicionado'];
function valorHistorico($valor): string {if(is_array($valor))return $valor?implode(', ',array_map('strval',$valor)):'Nenhum';if($valor===null||$valor==='')return 'Não informado';return (string)$valor;}
function dataHoraHistorico(?string $data): string {if(!$data)return '-';$d=new DateTime($data);return $d->format('d/m/Y \à\s H:i:s');}
function tamanhoArquivo(int $bytes): string {if($bytes>=1048576)return number_format($bytes/1048576,1,',','.').' MB';if($bytes>=1024)return number_format($bytes/1024,1,',','.').' KB';return $bytes.' bytes';}
$sit=statusPrazo($processo['data_vencimento'],$processo['status']);$titulo='Visualizar processo';require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div><h1>Visualizar processo</h1><p>Consulta completa e histórico de alterações do processo.</p></div><div class="page-actions"><a class="btn btn-ghost" href="prazos.php">Voltar</a><a class="btn btn-primary" href="prazo_form.php?id=<?=$id?>">Editar processo</a></div></section>
<section class="panel process-view"><div class="panel-head process-hero"><div><span class="process-eyebrow">PROCESSO</span><h2><?=e($processo['numero_processo'])?></h2><p><?=e($processo['assunto'])?></p></div><span class="status <?=$sit['classe']?>"><?=e($sit['texto'])?></span></div><dl class="process-details"><div><dt>Status atual</dt><dd><strong><?=e($processo['status'])?></strong></dd></div><div><dt>Data de entrada</dt><dd><?=dataBr($processo['data_entrada'])?></dd></div><div><dt>Data de vencimento</dt><dd><?=dataBr($processo['data_vencimento'])?></dd></div><div><dt>Procuradores vinculados</dt><dd><?=e($processo['procuradores_nomes']?:'Não vinculado')?></dd></div><div><dt>Cadastrado por</dt><dd><?=e($processo['criador_nome']?:'Usuário não disponível')?></dd></div><div><dt>Cadastrado em</dt><dd><?=e(dataHoraHistorico($processo['criado_em']))?></dd></div><div class="detail-wide"><dt>Observações</dt><dd><?=nl2br(e($processo['observacoes']?:'Sem observações'))?></dd></div></dl></section>
<div class="process-extras">
<section class="panel process-extra" id="comentarios"><div class="panel-head"><div><h2>Comentários</h2><p>Novas anotações são acrescentadas sem substituir as observações existentes.</p></div></div><div class="extra-body">
<?php if(($_GET['comentario']??'')==='ok'):?><div class="alert alert-success">Comentário adicionado.</div><?php endif;?>
<form method="post" action="processo_comentario_adicionar.php" class="form extra-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="prazo_id" value="<?=$id?>"><label>Novo comentário<textarea name="comentario" rows="4" maxlength="5000" required placeholder="Registre uma nova informação sobre o processo"></textarea></label><div class="form-actions"><button class="btn btn-primary" type="submit">Adicionar comentário</button></div></form>
<div class="comment-list"><?php if(!$comentarios):?><p class="empty">Nenhum comentário adicionado.</p><?php else:?><?php foreach($comentarios as $comentario):?><article class="comment-card"><div><strong><?=e($comentario['autor']?:'Usuário removido')?></strong><time><?=e(dataHoraHistorico($comentario['criado_em']))?></time></div><p><?=nl2br(e($comentario['comentario']))?></p></article><?php endforeach;?><?php endif;?></div>
</div></section>
<section class="panel process-extra" id="anexos"><div class="panel-head"><div><h2>Anexos</h2><p>PDF, imagens, Word ou Excel, com até 10 MB por arquivo.</p></div></div><div class="extra-body">
<?php if(($_GET['anexo']??'')==='ok'):?><div class="alert alert-success">Anexo enviado com segurança.</div><?php endif;?>
<form method="post" action="processo_anexo_enviar.php" enctype="multipart/form-data" class="form extra-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="prazo_id" value="<?=$id?>"><input type="hidden" name="MAX_FILE_SIZE" value="10485760"><label>Selecionar arquivo<input type="file" name="anexo" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx" required></label><div class="form-actions"><button class="btn btn-primary" type="submit">Enviar anexo</button></div></form>
<div class="attachment-list"><?php if(!$anexos):?><p class="empty">Nenhum anexo enviado.</p><?php else:?><?php foreach($anexos as $anexo):?><article class="attachment-card"><div><strong><?=e($anexo['nome_original'])?></strong><small><?=e(tamanhoArquivo((int)$anexo['tamanho']))?> · <?=e($anexo['autor']?:'Usuário removido')?> · <?=e(dataHoraHistorico($anexo['criado_em']))?></small></div><a class="btn btn-ghost btn-sm" href="processo_anexo_baixar.php?id=<?=(int)$anexo['id']?>">Baixar</a></article><?php endforeach;?><?php endif;?></div>
</div></section>
</div>
<section class="panel audit-process"><div class="panel-head"><div><h2>Auditoria do processo</h2><p>Histórico cronológico desde o cadastro até a conclusão.</p></div></div><div class="process-timeline">
<?php if(!$temCadastro):?><article class="timeline-item"><span class="timeline-dot"></span><div class="timeline-card"><div class="timeline-head"><strong>Cadastro original</strong><time><?=e(dataHoraHistorico($processo['criado_em']))?></time></div><p>Processo cadastrado por <strong><?=e($processo['criador_nome']?:'usuário não disponível')?></strong>. Registro anterior à auditoria detalhada.</p></div></article><?php endif;?>
<?php foreach($historico as $h):$det=json_decode($h['detalhes']??'',true)?:[];$mudancas=$det['mudancas']??[];$dados=$det['dados']??[];?><article class="timeline-item"><span class="timeline-dot"></span><div class="timeline-card"><div class="timeline-head"><strong><?=e($acoes[$h['acao']]??ucfirst(str_replace('_',' ',$h['acao'])))?></strong><time><?=e(dataHoraHistorico($h['criado_em']))?></time></div><p>Realizado por <strong><?=e($h['ator']?:'Sistema/usuário removido')?></strong><?php if($h['ator']&&$h['efetivo']&&$h['ator']!==$h['efetivo']):?> usando a conta de <strong><?=e($h['efetivo'])?></strong><?php endif;?> · IP <?=e($h['ip']?:'não registrado')?></p>
<?php if($dados):?><div class="change-list"><?php foreach($dados as $campo=>$valor):?><div><span><?=e($rotulos[$campo]??$campo)?></span><strong><?=e(valorHistorico($valor))?></strong></div><?php endforeach;?></div><?php endif;?>
<?php if($mudancas):?><div class="change-list"><?php foreach($mudancas as $campo=>$valores):?><div><span><?=e($rotulos[$campo]??$campo)?></span><del><?=e(valorHistorico($valores['antes']??null))?></del><b>→</b><ins><?=e(valorHistorico($valores['depois']??null))?></ins></div><?php endforeach;?></div><?php elseif(!$dados&&empty($det)):?><p class="muted-text">Esta ação não possui detalhes adicionais.</p><?php endif;?></div></article><?php endforeach;?>
</div></section><?php require __DIR__.'/includes/footer.php';?>
